arch: vit_small
batch_size: 16
clip_grad: 0 #lipping with norm .3 ~ 1.0 can  help optimization for larger ViT architectures. 0 for disabling.
epochs: 400
gpu: 0
moco: True
queue_len: 10000
stop_grad_conv1: True
wandb: new-submission-TRYOUT
