# wandb: big_run_vit
data: ../imagenette2
use_bn: True
epochs: 200
no_leaky: True  #False means leaky relu. True mean relu
batch_size: 8
subset: 0
cos: True
final_lr: 0.000048
num_hidden: 2
queue_len: 10000
arch: vit_tiny
sgd: False
stop_grad_conv1: True
warmup_epochs: 20
gpu: 0
lr: 0.00015
wd: 0.1
cos: True

