# wandb: big_run_vit
data: ./tiny_dataset
use_bn: True
epochs: 100
no_leaky: True  #False means leaky relu. True mean relu
batch_size: 32
subset: 0
cos: True
final_lr: 0.00048
num_hidden: 2
queue_len: 10000
arch: vit_tiny
sgd: False
stop_grad_conv1: True


