# wandb: vit_adamW
data: ./tiny_dataset
use_bn: True
epochs: 200
no_leaky: True  #False means leaky relu. True mean relu
batch_size: 32
subset: 0
cos: True
final_lr: 0.00048
lr: 0.005
num_hidden: 2
queue_len: 10000
arch: vit_base
sgd: False
stop_grad_conv1: True
warmup_epochs: 20
gpu: 0
wd: 0.1
cos: True
moco: True

