# wandb: big_run
use_bn: True
data: ./tiny_dataset
epochs: 100
sgd: True
no_leaky: False  #False means leaky relu. True mean relu
batch_size: 16
subset: 0
cos: True
final_lr: 0.0048
num_hidden: 2
queue_len: 100
arch: vit_tiny
moco: True

