wandb: original_parameters
data: ../imagenette2
use_bn: True
epochs: 400
no_leaky: False  #False means leaky relu. True mean relu
batch_size: 16
cos: True
final_lr: 0.0048
lr: 4.8
num_hidden: 2
queue_len: 10000
arch: resnet18
gpu: 0
cos: True
sgd: True

