wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.6
    start_time: 1668071095.556803
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.6
      5: 0.13.5
      8:
      - 5
arch:
  desc: null
  value: resnet18
batch_size:
  desc: null
  value: 2
cls_size:
  desc: null
  value:
  - 5
col_tau:
  desc: null
  value: 0.05
config:
  desc: null
  value:
  - 0.05
  - 0.4
cos:
  desc: null
  value: false
data:
  desc: null
  value: ./tiny_dataset
dim:
  desc: null
  value: 128
epochs:
  desc: null
  value: 800
eps:
  desc: null
  value: 1.0e-12
final_lr:
  desc: null
  value: null
fixed_cls:
  desc: null
  value: false
global_crops_scale:
  desc: null
  value:
  - 0.4
  - 1.0
hidden_dim:
  desc: null
  value: 4096
lars:
  desc: null
  value: false
local_config:
  desc: null
  value: configs/config_first_run.yaml
local_crops_number:
  desc: null
  value: 6
local_crops_scale:
  desc: null
  value:
  - 0.05
  - 0.4
lr:
  desc: null
  value: 4.8
momentum:
  desc: null
  value: 0.9
no_leaky:
  desc: null
  value: false
num_cls:
  desc: null
  value: 1
num_hidden:
  desc: null
  value: 3
pretrained:
  desc: null
  value: null
print_freq:
  desc: null
  value: 16
resume:
  desc: null
  value: ''
row_tau:
  desc: null
  value: 0.1
save_path:
  desc: null
  value: ./saved/
seed:
  desc: null
  value: 0
sgd:
  desc: null
  value: false
start_epoch:
  desc: null
  value: 0
start_warmup:
  desc: null
  value: 0.3
use_amp:
  desc: null
  value: true
use_bn:
  desc: null
  value: false
wandb:
  desc: null
  value: debug_code
warmup_epochs:
  desc: null
  value: 10
weight_decay:
  desc: null
  value: 1.0e-06
